Added updated validators
gnosischain/documentation pull request #100
Opened 2022-08-25 18:41 UTC by CJBangert

## What

- added updated validators
- got rid of circular reference in the AMB/OmniBridge validators sections

## Refs

- #83

2022-08-26 12:12 UTC, dan-gnosis requested changes
@CJBangert Some minor changes requested. Good work

2022-08-26 12:12 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +The AMB bridge relies on a trusted group of [AMB Bridge Validators](omnibridge#current-bridge-validators), who are known Gnosis community members. The same [validator set](omnibridge#current-bridge-v
**Thought:** Should we list the Validators in the AMB section, instead of the Omnibridge section?

**Reasoning:** The Omnibridge is actually an extension built on-top of the Arbitrary Message Bridge

2022-08-26 12:12 UTC, dan-gnosis commented on docs/bridges/tokenbridge/omnibridge.md
> +<TabItem value="eth-gc" label="Eth<->Gnosis">
Small change: Consistent formatting required (e.g. spacing and symbol used to represent bridge)

- ETH<->Gnosis
- BNB Chain <-> Gnosis

Another thought is to standardize <-> as a symbol for bridging

<img width="936" alt="image" src="https://user-images.githubusercontent.com/98335261/186900222-027e9546-fce8-4b0a-9940-059af723fc1c.png">

2022-08-26 12:12 UTC, dan-gnosis commented on docs/bridges/tokenbridge/omnibridge.md
> -| [0x459A3bd49F1ff109bc90b76125533699AaAAf9A6](https://gnosisscan.io/address/0x459A3bd49F1ff109bc90b76125533699AaAAf9A6) | Protofire         |
Use EIP-3770 address formats, especially in cross-chain bridging

https://eips.ethereum.org/EIPS/eip-3770

![image](https://user-images.githubusercontent.com/98335261/186900723-e724fff7-9b41-4b4f-9f2a-6160450a7c99.png)

2022-08-26 12:12 UTC, dan-gnosis commented on docs/bridges/tokenbridge/omnibridge.md
> +| [0x105cd22ed3d089bf5589c59b452f9de0796ca52d](https://gnosisscan.io/address/0x105CD22eD3D089Bf5589C59b452f9dE0796Ca52d) | Giveth            |
EIP-3770 addresses

2022-08-26 12:12 UTC, dan-gnosis commented on docs/bridges/tokenbridge/omnibridge.md
> + For a message/tokens to be relayed to another network, bridge validators need to affirm the transaction. Bridge validators are run by trusted members of the Gnosis community. The [long-term roadmap]
Good summary

2022-08-26 12:27 UTC, CJBangert commented on docs/bridges/tokenbridge/amb-bridge.md
> +The AMB bridge relies on a trusted group of [AMB Bridge Validators](omnibridge#current-bridge-validators), who are known Gnosis community members. The same [validator set](omnibridge#current-bridge-v
That makes sense

2022-08-29 23:07 UTC, dan-gnosis approved these changes

2022-08-29 23:07 UTC, merged