Adding Rainbowkit + Wagmi Explanation and Gnosis Chain setup
gnosischain/documentation pull request #134
Opened 2022-09-16 15:53 UTC by billyjitsu

## Adding Guide to "Interacting with Gnosis"

- Created a new section called "Using Rainbow Kit + Wagmi" that explains how to setup Rainbow Kit/Wagmi to accept Gnosis Chain as a custom chain

Adding sidebar.js link,  Interact/Readme link, and adding Rainbowkit+Wagmi guide within structure

2022-09-20 14:21 UTC, alebanzas requested changes
Thanks @billyjitsu ! I would only add some links to the current RPC providers to make the guide "provider agnostic".

2022-09-20 14:21 UTC, alebanzas commented on docs/developers/interact/rainbowkit-wagmi.mdx
> +Now that we imported it, we can add it to our "configureChains" hook and set it up. You will see the "jsonRpcProvider" is on the top of alchemy and public. **It is manually setup to use the Gnosis Ch
I will add here a link to https://docs.gnosischain.com/tools/rpc/

2022-09-20 15:09 UTC, billyjitsu commented on docs/developers/interact/rainbowkit-wagmi.mdx
> +Now that we imported it, we can add it to our "configureChains" hook and set it up. You will see the "jsonRpcProvider" is on the top of alchemy and public. **It is manually setup to use the Gnosis Ch
Pushed with changes

2022-09-21 08:36 UTC, alebanzas approved these changes
lgtm, thanks @billyjitsu !

2022-09-21 08:38 UTC, merged