Add Nimbus and Erigon guide
gnosischain/documentation pull request #408
Opened 2023-03-16 07:44 UTC by zengzengzenghuy

## What
* Add Nimbus **docker-compose.yml** configuration
* Add Erigon CLI guide

## Refs
### Nimbus
* https://github.com/gnosischain/gnosis-nimbus-eth2
* https://nimbus.guide/
### Erigon
* https://github.com/ledgerwatch/erigon#documentation

2023-03-16 21:05 UTC, filoozom reviewed
A few nitpicks, but in general great work! Looking forward to this shipping. 😁

2023-03-16 21:05 UTC, filoozom commented on docs/node/guide/beacon/_partials/_install_cl_nimbus.md
> +Nimbus is not ready for production use. Currently, you can only use Docker to run Nimbus Beacon Node + Validator.
```suggestion
:::caution
Nimbus is considered experimental for Gnosis and only supports Docker deployments for now. For production ready alternatives, please consider Lighthouse, Teku or Lodestar.
```

2023-03-16 21:05 UTC, filoozom commented on docs/node/guide/execution/_partials/_install_el_erigon.md
> +[Erigon](https://github.com/ledgerwatch/erigon#documentation) is not ready for production use. Please consider switching to Nethermind.
```suggestion
:::caution
[Erigon](https://github.com/ledgerwatch/erigon#documentation) is considered experimental for Gnosis. For production use, please consider Nethermind.
```

2023-03-20 09:43 UTC, filoozom commented on docs/node/guide/beacon/nimbus.md
> +- [https://github.com/gnosischain/gnosis-nimbus-eth2](https://github.com/gnosischain/gnosis-nimbus-eth2)
My bad, that's indeed correct 😅

2023-03-20 09:48 UTC, zengzengzenghuy commented on docs/node/guide/execution/erigon.md
> +WIP
Done in [cadbb26](https://github.com/gnosischain/documentation/pull/408/commits/cadbb26f053e3a218efe534cee5c44210ebca9c4)

2023-03-23 14:46 UTC, filoozom requested changes
The Nimbus docs look good, for the Erigon ones I would like to have them a bit more like the Nethermind ones. Currently, it's missing a few steps that would make it incompatible with how the way the CL docs are written.

At least, we should add:
- The folder structure
- The `version` in `docker-compose.yaml`
- The `gnsosi_net` network
- All the other steps
  - Archive node vs pruned node
  - JWT Secret
  - Start container
  - Monitor logs
  - Updating your node

We should also change:
- The volume paths (`/home/$USER/gnosis/execution`, same for the jwt)

2023-03-28 15:17 UTC, filoozom commented on docs/node/guide/execution/erigon.md
>      restart: unless-stopped
Not sure why I can't suggest changes anymore, but we're missing the network here:
```
        networks:
          - gnosis_net
```

2023-03-31 06:13 UTC, zengzengzenghuy commented on docs/node/guide/execution/erigon.md
> +mkdir ./data && sudo chown 1000:1000 ./data
Change `/data` to `/execution` [e34d0a4](https://github.com/gnosischain/documentation/pull/408/commits/e34d0a472025bb4c53137ac105bdb65a7dde1a43)

2023-03-31 12:22 UTC, filoozom approved these changes

2023-04-02 13:14 UTC, merged