Gnosis Chain with Dynamic
gnosischain/documentation pull request #414
Opened 2023-03-29 08:58 UTC by turbahn

Adding documentation on how to use Gnosis Chain with Dynamic

## What

- Dynamic is a free multi-chain wallet adapter with built in support for Gnosis Chain. We are proposing adding a guide to the Gnosis documentation next to other wallet libraries describing how to easily support Gnosis.

Note: I did not include the update to the overall documentation link structure as I assume that will be controlled by repo owners, but let me know if you'd like me to add it. Thanks!

The PR also includes a demo environment showing a full end to end working demo of the integration: https://codesandbox.io/s/dynamic-gnosis-chain-demo-vzps4b

## Refs

Tackles two issues:
- Add Dynamic as an infra provider: https://github.com/gnosischain/documentation/issues/412
- Create a guide for how to use Dynamic with Gnosis Chain: https://github.com/gnosischain/documentation/issues/413

2023-03-30 05:47 UTC, zengzengzenghuy requested changes
Thanks for contributing. @turbahn 
Added a request to fix error.

2023-03-30 05:47 UTC, zengzengzenghuy commented on docs/developers/interact/dynamic.mdx
> +<img width="600" alt="Gnosis_new" src="https://user-images.githubusercontent.com/1596208/228478128-925acb34-1f5d-45a5-bd2a-c6467af265a7.png">
should append `</img>` to prevent `Unterminated JSX contents` error.  @turbahn

2023-03-30 06:00 UTC, filoozom commented on docs/developers/interact/dynamic.mdx
> +<img width="600" alt="Gnosis_new" src="https://user-images.githubusercontent.com/1596208/228478128-925acb34-1f5d-45a5-bd2a-c6467af265a7.png">
Just a heads-up: you'd typically use self-closing tags for void elements in HTML / JSX, so `<img ... />` instead of `<img ...></img>`.

2023-03-31 05:55 UTC, zengzengzenghuy approved these changes
Thanks @turbahn

2023-03-31 05:55 UTC, merged