WIP: 54 amb bridge first pass
gnosischain/documentation pull request #67
Opened 2022-08-12 22:21 UTC by CJBangert

## What

- added details about how the Arbitrary message bridge works
- TODO: uodate diagrams, fill in governance params. Will also probably be a good idea to get someone more familiar (maybe someone from the Omnibridge/Tokenbridge team) to give it a look-over

## Refs

- #54

2022-08-17 15:58 UTC, alebanzas commented
@dan-gnosis could you review it? thanks!!

2022-08-17 23:55 UTC, dan-gnosis requested changes
Good work. Some changes but headed in the right direction.

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +| Bug Reporting         | On the Immunefi site [here](https://immunefi.com/bounty/gnosischain/) |
[Immunefi](https://immunefi.com/bounty/gnosischain/)

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +| AMB/Omnibridge Multi-Token Mediator | 0x88ad09518695c6c3712AC10a214bE5109a655671 |
Link Etherscan address (preferably the page where you can interact with the contract)

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +| AMB/Omnibridge Multi-Token Mediator | 0xf6A78083ca3e2a662D6dd1703c939c8aCE2e268d |
Link Gnosisscan address, e.g. 

https://gnosisscan.io/address/0xf6a78083ca3e2a662d6dd1703c939c8ace2e268d#code

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +* __Home (Native) Network__: Of the two networks being bridged between, the home or native network is the one with fast and inexpensive operations. All bridge operations to collect validator confirma
This is actually quite concerning from a Bridge Design perspective. That means that reverse bridge-out operations are wholly witnessed on Gnosis Chain, with no signatories on Ethereum L1.

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> + ![](/img/bridges/diagrams/amb-bridge-contract-flow.png)
Where is the contract which holds this method?

I don't see it in: 
https://gnosisscan.io/address/0xf6a78083ca3e2a662d6dd1703c939c8ace2e268d#readProxyContract

EDIT: 
I verified the contract as a proxy on Gnosisscan.io, and was able to find the method below

https://gnosisscan.io/address/0x75Df5AF045d91108662D8080fD1FEFAd6aA0bb59#writeProxyContract

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +### Call a cross-chain method via AMB:
I highly recommend we also add this, later on, as a tutorial in the Developer Docs

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +1. User calls `foo()` on an originator contract
What is an originator contract? Needs clearer term

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +2. Originator contract calls `requireToPassMessage()` on Foreign Bridge contract, and encodes `foo()`, target address, and includes some tokens for gas.
Does the "Foreign Bridge contract" here use the same terminology as above (e.g. Home, vs Foreign)? 

Longer term, I think we need to clean up some of the nomenclature. An idea is to default to a different dichotomy: 

- Originating vs Receiving
- Expensive vs Cheaper

An edge case that I see from this dichotomy is a Originating chain that is Cheaper, so most of the validations is done on the Cheaper chain

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +AMB Bridge proxy contact on Ethereum can be viewed [here](https://etherscan.io/address/0x4C36d2919e407f0Cc2Ee3c993ccF8ac26d9CE64e)
Avoid using "here" for hyperlinks - it's not SEO-friendly. 

I would advise to just link [AMB Bridge Proxy Contract on Ethereum](https://etherscan.io/address/0x4C36d2919e407f0Cc2Ee3c993ccF8ac26d9CE64e) directly. 

Also, when linking to Etherscan or Gnosisscan, default to the #code or #writeProxyContract page, which shows the underlying methods. 

![image](https://user-images.githubusercontent.com/98335261/185262876-d1525280-33ca-4faf-afe3-c32ddd5360c7.png)

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +AMB Bridge Proxy Contract and Gnosis can be viewed [here](https://blockscout.com/xdai/mainnet/address/0x75Df5AF045d91108662D8080fD1FEFAd6aA0bb59)
See above

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> + A mediator contract is needed if there is an approval flow, such as when transferring an NFT or ERC-20. For a more in-depth explanation, see the [Omnibridge page](omnibridge).
I'm not sure if the Omnibridge page explains the Mediator Contracts at all

2022-08-17 23:55 UTC, dan-gnosis commented on docs/bridges/tokenbridge/amb-bridge.md
> +#### Bridge Modes
I recommend we turn this into a Heading 3, and describe it differently: 

### "Uses of AMB"

- ERC-to-ERC Bridges: ...
- ERC-to-Native Bridges: ...
- Message Passing: ...

2022-08-18 13:09 UTC, CJBangert commented on docs/bridges/tokenbridge/amb-bridge.md
> + ![](/img/bridges/diagrams/amb-bridge-contract-flow.png)
Yep, my understanding is the mediator contract would call that function on the bridge contract

2022-08-18 13:29 UTC, CJBangert commented on docs/bridges/tokenbridge/amb-bridge.md
> +2. Originator contract calls `requireToPassMessage()` on Foreign Bridge contract, and encodes `foo()`, target address, and includes some tokens for gas.
Yes, this is the same terminology as above. I've just stuck to using the terminology used in the code up through now but I agree it is confusing

2022-08-18 13:36 UTC, CJBangert commented on docs/bridges/tokenbridge/amb-bridge.md
> + A mediator contract is needed if there is an approval flow, such as when transferring an NFT or ERC-20. For a more in-depth explanation, see the [Omnibridge page](omnibridge).
Working across 2 branches, going to go back through and add a sub-heading to link to

2022-08-18 14:28 UTC, CJBangert commented on docs/bridges/tokenbridge/amb-bridge.md
> +1. User calls `foo()` on an originator contract
I changed it to "originating contract" and added a definition under terminology. This is just an arbitrary contract that the user interacts with where the message originates.

2022-08-18 17:45 UTC, CJBangert commented
link will be broken until omnibridge branch is merged

2022-08-18 18:18 UTC, dan-gnosis approved these changes

2022-08-18 18:18 UTC, merged