WIP: 56 omnibridge first pass
gnosischain/documentation pull request #71
Opened 2022-08-16 20:25 UTC by CJBangert

## What

- add details on how omnibridge works
- add contract addresses
- TODO: add another diagram for withdrawl

## Refs

- #56

2022-08-17 23:30 UTC, dan-gnosis commented on docs/bridges/tokenbridge/omnibridge.md
> +| Bug Bounty            | [upp to $2m](https://immunefi.com/bounty/gnosischain/) |
Typo - 'Up', not 'Upp'

2022-08-17 23:31 UTC, dan-gnosis commented on docs/bridges/tokenbridge/omnibridge.md
> +| Bug Reporting         | On the Immunefi site [here](https://immunefi.com/bounty/gnosischain/) |
Just say [Immunefi](https://immunefi.com/bounty/gnosischain/)

2022-08-17 23:32 UTC, dan-gnosis commented on docs/bridges/tokenbridge/omnibridge.md
> +| Omnibridge Multi-Token Mediator | 0x88ad09518695c6c3712AC10a214bE5109a655671 |
Please link these addresses with the Etherscan links

2022-08-17 23:33 UTC, dan-gnosis requested changes
Good work. Some minor typos and improvements needed.

2022-08-17 23:33 UTC, dan-gnosis commented on docs/bridges/tokenbridge/omnibridge.md
> +| Proxy Contract                | 0x75Df5AF045d91108662D8080fD1FEFAd6aA0bb59 |
Please link the Blockscout or Gnosisscan addresses

2022-08-17 23:33 UTC, dan-gnosis commented on docs/bridges/tokenbridge/omnibridge.md
>  ![](/img/bridges/diagrams/token-bridge.svg)
I'll help to clean this up tomorrow

2022-08-18 16:27 UTC, dan-gnosis commented
Looks good to go!

2022-08-18 17:03 UTC, alebanzas commented on docs/bridges/tokenbridge/omnibridge.md
>  ![](/img/bridges/diagrams/token-bridge.svg)
Is this ready?

2022-08-18 17:03 UTC, alebanzas commented
Thanks @CJBangert and @dan-gnosis .

There is a conflict with `main` to merge.

2022-08-18 17:32 UTC, merged